# Copyright (c) Nebari Development Team.
# Distributed under the terms of the Modified BSD License.

# pre-commit is a tool to perform a predefined set of tasks manually and/or
# automatically before git commits are made.
#
# Config reference: https://pre-commit.com/#pre-commit-configyaml---top-level
#
# Common tasks
#
# - Register git hooks: pre-commit install --install-hooks
# - Run on all files:   pre-commit run --all-files
ci:
  autoupdate_schedule: monthly
  autofix_commit_msg: |
    [pre-commit.ci] Apply automatic pre-commit fixes

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: detect-private-key
      - id: end-of-file-fixer

  # Autoformat: Python code
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black

  # Autoformat: Python code - sort imports
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args: ["--profile", "black"]

  # Markdown, json, toml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        types: [markdown, toml]

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.19.11
    hooks:
      - id: djlint-jinja
        types_or: ["html"]
