name: "Release"

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      qhub_tag:
        description: 'Tag for test PyPI release'
jobs:
  release:
    name: 'PyPi Release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Infastructure'
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install twine
        run: |
          pip install twine

      - name: Build and Distribute
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist
          twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: GH Release
        uses: softprops/action-gh-release@v1
        name: Version ${{ env.RELEASE_VERSION }}
